package ruiseki.okbackpack;

import ruiseki.okbackpack.common.block.BlockDiamondBackpackConfig;
import ruiseki.okbackpack.common.block.BlockGoldBackpackConfig;
import ruiseki.okbackpack.common.block.BlockIronBackpackConfig;
import ruiseki.okbackpack.common.block.BlockLeatherBackpackConfig;
import ruiseki.okbackpack.common.block.BlockObsidianBackpackConfig;
import ruiseki.okbackpack.common.block.BlockSleepingBagConfig;
import ruiseki.okbackpack.common.item.ItemUpgradeConfig;
import ruiseki.okbackpack.common.item.anvil.ItemAnvilUpgradeConfig;
import ruiseki.okbackpack.common.item.arcane.ItemArcaneCraftingUpgradeConfig;
import ruiseki.okbackpack.common.item.battery.ItemBatteryUpgradeConfig;
import ruiseki.okbackpack.common.item.compacting.ItemAdvancedCompactingUpgradeConfig;
import ruiseki.okbackpack.common.item.compacting.ItemCompactingUpgradeConfig;
import ruiseki.okbackpack.common.item.crafting.ItemCraftingUpgradeConfig;
import ruiseki.okbackpack.common.item.deposit.ItemAdvancedDepositUpgradeConfig;
import ruiseki.okbackpack.common.item.deposit.ItemDepositUpgradeConfig;
import ruiseki.okbackpack.common.item.energizednode.ItemEnergizedNodeUpgradeConfig;
import ruiseki.okbackpack.common.item.everlasting.ItemEverlastingUpgradeConfig;
import ruiseki.okbackpack.common.item.feeding.ItemAdvancedFeedingUpgradeConfig;
import ruiseki.okbackpack.common.item.feeding.ItemFeedingUpgradeConfig;
import ruiseki.okbackpack.common.item.filter.ItemAdvancedFilterUpgradeConfig;
import ruiseki.okbackpack.common.item.filter.ItemFilterUpgradeConfig;
import ruiseki.okbackpack.common.item.inception.ItemInceptionUpgradeConfig;
import ruiseki.okbackpack.common.item.infinity.ItemInfinityUpgradeConfig;
import ruiseki.okbackpack.common.item.infinity.ItemSurvivalInfinityUpgradeConfig;
import ruiseki.okbackpack.common.item.jukebox.ItemAdvancedJukeBoxUpgradeConfig;
import ruiseki.okbackpack.common.item.jukebox.ItemJukeBoxUpgradeConfig;
import ruiseki.okbackpack.common.item.magnet.ItemAdvancedMagnetUpgradeConfig;
import ruiseki.okbackpack.common.item.magnet.ItemMagnetUpgradeConfig;
import ruiseki.okbackpack.common.item.pickup.ItemAdvancedPickupUpgradeConfig;
import ruiseki.okbackpack.common.item.pickup.ItemPickupUpgradeConfig;
import ruiseki.okbackpack.common.item.pump.ItemAdvancedPumpUpgradeConfig;
import ruiseki.okbackpack.common.item.pump.ItemPumpUpgradeConfig;
import ruiseki.okbackpack.common.item.pump.xp.ItemXpPumpUpgradeConfig;
import ruiseki.okbackpack.common.item.refill.ItemAdvancedRefillUpgradeConfig;
import ruiseki.okbackpack.common.item.refill.ItemRefillUpgradeConfig;
import ruiseki.okbackpack.common.item.restock.ItemAdvancedRestockUpgradeConfig;
import ruiseki.okbackpack.common.item.restock.ItemRestockUpgradeConfig;
import ruiseki.okbackpack.common.item.smelter.ItemAutoBlastingUpgradeConfig;
import ruiseki.okbackpack.common.item.smelter.ItemAutoSmeltingUpgradeConfig;
import ruiseki.okbackpack.common.item.smelter.ItemAutoSmokingUpgradeConfig;
import ruiseki.okbackpack.common.item.smelter.ItemBlastingUpgradeConfig;
import ruiseki.okbackpack.common.item.smelter.ItemSmeltingUpgradeConfig;
import ruiseki.okbackpack.common.item.smelter.ItemSmokingUpgradeConfig;
import ruiseki.okbackpack.common.item.stack.ItemStackUpgradeConfig;
import ruiseki.okbackpack.common.item.tank.ItemTankUpgradeConfig;
import ruiseki.okbackpack.common.item.toolswapper.ItemAdvancedToolSwapperUpgradeConfig;
import ruiseki.okbackpack.common.item.toolswapper.ItemToolSwapperUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.bat.ItemBatUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.blaze.ItemBlazeUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.bookshelf.ItemBookshelfUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.cactus.ItemCactusUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.cake.ItemCakeUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.chicken.ItemChickenUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.cow.ItemCowUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.creeper.ItemCreeperUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.dragon.ItemDragonUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.ghast.ItemGhastUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.glowstone.ItemGlowstoneUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.hay.ItemHayUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.lapis.ItemLapisUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.magma.ItemMagmaCubeUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.ocelot.ItemOcelotUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.quartz.ItemQuartzUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.quiver.ItemQuiverUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.rainbow.ItemRainbowUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.redstone.ItemRedstoneUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.slime.ItemSlimeUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.spider.ItemSpiderUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.sponge.ItemSpongeUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.squid.ItemSquidUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.wither.ItemWitherUpgradeConfig;
import ruiseki.okbackpack.common.item.travelers.wolf.ItemWolfUpgradeConfig;
import ruiseki.okbackpack.common.item.voiding.ItemAdvancedVoidUpgradeConfig;
import ruiseki.okbackpack.common.item.voiding.ItemVoidUpgradeConfig;
import ruiseki.okbackpack.compat.Mods;
import ruiseki.okcore.config.ConfigHandler;

public class Configs {

    public static void registerBlocks(ConfigHandler configHandler) {
        // Blocks
        configHandler.add(new BlockLeatherBackpackConfig());
        configHandler.add(new BlockIronBackpackConfig());
        configHandler.add(new BlockGoldBackpackConfig());
        configHandler.add(new BlockDiamondBackpackConfig());
        configHandler.add(new BlockObsidianBackpackConfig());
        configHandler.add(new BlockSleepingBagConfig());

        // Items
        configHandler.add(new ItemUpgradeConfig());
        configHandler.add(new ItemAnvilUpgradeConfig());
        configHandler.add(new ItemBatteryUpgradeConfig());
        configHandler.add(new ItemCompactingUpgradeConfig());
        configHandler.add(new ItemAdvancedCompactingUpgradeConfig());
        configHandler.add(new ItemCraftingUpgradeConfig());
        configHandler.add(new ItemDepositUpgradeConfig());
        configHandler.add(new ItemAdvancedDepositUpgradeConfig());
        configHandler.add(new ItemEverlastingUpgradeConfig());
        configHandler.add(new ItemFeedingUpgradeConfig());
        configHandler.add(new ItemAdvancedFeedingUpgradeConfig());
        configHandler.add(new ItemFilterUpgradeConfig());
        configHandler.add(new ItemAdvancedFilterUpgradeConfig());
        configHandler.add(new ItemInceptionUpgradeConfig());
        configHandler.add(new ItemInfinityUpgradeConfig());
        configHandler.add(new ItemSurvivalInfinityUpgradeConfig());
        configHandler.add(new ItemJukeBoxUpgradeConfig());
        configHandler.add(new ItemAdvancedJukeBoxUpgradeConfig());
        configHandler.add(new ItemMagnetUpgradeConfig());
        configHandler.add(new ItemAdvancedMagnetUpgradeConfig());
        configHandler.add(new ItemPickupUpgradeConfig());
        configHandler.add(new ItemAdvancedPickupUpgradeConfig());
        configHandler.add(new ItemPumpUpgradeConfig());
        configHandler.add(new ItemAdvancedPumpUpgradeConfig());
        configHandler.add(new ItemXpPumpUpgradeConfig());
        configHandler.add(new ItemRefillUpgradeConfig());
        configHandler.add(new ItemAdvancedRefillUpgradeConfig());
        configHandler.add(new ItemRestockUpgradeConfig());
        configHandler.add(new ItemAdvancedRestockUpgradeConfig());
        configHandler.add(new ItemBlastingUpgradeConfig());
        configHandler.add(new ItemSmeltingUpgradeConfig());
        configHandler.add(new ItemSmokingUpgradeConfig());
        configHandler.add(new ItemAutoBlastingUpgradeConfig());
        configHandler.add(new ItemAutoSmeltingUpgradeConfig());
        configHandler.add(new ItemAutoSmokingUpgradeConfig());
        configHandler.add(new ItemStackUpgradeConfig());
        configHandler.add(new ItemTankUpgradeConfig());
        configHandler.add(new ItemToolSwapperUpgradeConfig());
        configHandler.add(new ItemAdvancedToolSwapperUpgradeConfig());
        configHandler.add(new ItemVoidUpgradeConfig());
        configHandler.add(new ItemAdvancedVoidUpgradeConfig());

        if (GeneralConfig.enableTravelersUpgrades) {
            configHandler.add(new ItemBatUpgradeConfig());
            configHandler.add(new ItemBlazeUpgradeConfig());
            configHandler.add(new ItemBookshelfUpgradeConfig());
            configHandler.add(new ItemCowUpgradeConfig());
            configHandler.add(new ItemCactusUpgradeConfig());
            configHandler.add(new ItemCakeUpgradeConfig());
            configHandler.add(new ItemChickenUpgradeConfig());
            configHandler.add(new ItemCreeperUpgradeConfig());
            configHandler.add(new ItemDragonUpgradeConfig());
            configHandler.add(new ItemGhastUpgradeConfig());
            configHandler.add(new ItemGlowstoneUpgradeConfig());
            configHandler.add(new ItemHayUpgradeConfig());
            configHandler.add(new ItemLapisUpgradeConfig());
            configHandler.add(new ItemMagmaCubeUpgradeConfig());
            configHandler.add(new ItemOcelotUpgradeConfig());
            configHandler.add(new ItemQuartzUpgradeConfig());
            configHandler.add(new ItemQuiverUpgradeConfig());
            configHandler.add(new ItemRainbowUpgradeConfig());
            configHandler.add(new ItemRedstoneUpgradeConfig());
            configHandler.add(new ItemSlimeUpgradeConfig());
            configHandler.add(new ItemSpiderUpgradeConfig());
            configHandler.add(new ItemSpongeUpgradeConfig());
            configHandler.add(new ItemSquidUpgradeConfig());
            configHandler.add(new ItemWitherUpgradeConfig());
            configHandler.add(new ItemWolfUpgradeConfig());
        }

        if (Mods.Thaumcraft.isModLoaded()) {
            if (GeneralConfig.enableArcaneCraftingUpgrade) {
                configHandler.add(new ItemArcaneCraftingUpgradeConfig());
            }
            configHandler.add(new ItemEnergizedNodeUpgradeConfig());
        }
    }
}
